"""empty message

Revision ID: 5ec6fe8452bd
Revises: 3081048415ff
Create Date: 2022-06-10 22:35:01.561000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ec6fe8452bd'
down_revision = '3081048415ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    op.add_column('artists', sa.Column('seeking_description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'seeking_description')
    op.drop_column('artists', 'seeking_talent')
    # ### end Alembic commands ###
